services:
  backend-app:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
  postgres:
    container_name: main-db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432

  redis:
    container_name: main-cache
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  postgres:
  redis: