services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432

  redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  postgres:
  redis: